package com.ninja6.antispeedrun.listeners;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.logging.Logger;

import org.bukkit.GameMode;
import org.bukkit.Location;
import org.bukkit.NamespacedKey;
import org.bukkit.World;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.event.world.LootGenerateEvent;
import org.bukkit.generator.structure.GeneratedStructure;
import org.bukkit.generator.structure.Structure;
import org.bukkit.generator.structure.StructurePiece;
import org.bukkit.plugin.Plugin;
import org.bukkit.util.BoundingBox;

import com.ninja6.antispeedrun.storage.ExploredStructureStore;

import io.papermc.paper.registry.RegistryAccess;
import io.papermc.paper.registry.RegistryKey;

/**
 * Records Ancient City exploration (#221) into {@link ExploredStructureStore}, where
 * {@code TrimProgressionManager} reads it for the Silence and Ward trims. The rules are
 * {@link AncientCityRules}; the writes are {@link AncientCityTracker}'s.
 *
 * <h2>Entering a city</h2>
 *
 * Each online player gets a repeating task on their own scheduler, every
 * {@link AncientCityRules#PERIOD_TICKS} ticks, started on join and, for players already online,
 * when the plugin enables. A player not yet recorded, in an overworld and at Deep Dark depth has the
 * Ancient City pieces referenced by their chunk read through Paper's structure API
 * ({@code World#getStructures}, then each {@code GeneratedStructure}'s pieces), and is recorded
 * when the block they stand in lies inside one. That is the test vanilla's location trigger applies
 * for a Bastion or an End City. Everyone else costs a position read and two comparisons.
 *
 * <h2>Loot</h2>
 *
 * A player who generates the loot of an Ancient City chest by opening it first is recorded under a
 * separate id, whatever {@code item-progression.count-structure-loot} says, and the toggle decides
 * at lookup whether that counts. Loot a plugin generates does not, nor does an NPC player's.
 *
 * <h2>Folia</h2>
 *
 * The task runs on the region thread that owns the player, which also owns the chunk they stand
 * in, and is retired with the player when they leave. The loot handler reads only the looter's UUID
 * and plugin metadata, so it is safe on whichever region fires it. The store is safe from any
 * thread and writes its file on the I/O executor.
 */
public final class AncientCityListener implements Listener {

    private final Plugin plugin;

    private final AncientCityTracker tracker;

    /** The Ancient City structure, or {@code null} when a datapack has removed it. */
    private final Structure city;

    public AncientCityListener(Plugin plugin, ExploredStructureStore explored, Logger logger) {
        this.plugin = Objects.requireNonNull(plugin, "plugin");
        this.tracker = new AncientCityTracker(explored);
        this.city = RegistryAccess.registryAccess().getRegistry(RegistryKey.STRUCTURE)
                .get(NamespacedKey.minecraft("ancient_city"));
        if (city == null) {
            Objects.requireNonNull(logger, "logger").warning("This server has no minecraft:ancient_city "
                    + "structure, so entering an Ancient City cannot be recorded; Silence and Ward trims "
                    + "open only from Ancient City chest loot while count-structure-loot is on.");
        }
    }

    /** Starts watching a player who has just joined. */
    @EventHandler(priority = EventPriority.MONITOR)
    public void onJoin(PlayerJoinEvent event) {
        track(event.getPlayer());
    }

    /**
     * Starts the repeating look at {@code player}'s position. Call once per player: on join, and
     * from {@code onEnable} for players already online. Safe from any thread.
     */
    public void track(Player player) {
        if (city == null) {
            return;
        }
        player.getScheduler().runAtFixedRate(plugin, task -> look(player), null,
                AncientCityRules.PERIOD_TICKS, AncientCityRules.PERIOD_TICKS);
    }

    /** An Ancient City chest's loot, generated by the player who opened it first. */
    @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = true)
    public void onLootGenerate(LootGenerateEvent event) {
        if (event.isPlugin() || !(event.getEntity() instanceof Player player)) {
            return;
        }
        tracker.looted(player.getUniqueId(), event.getLootTable().getKey(),
                PersonalCreditRules.creditable(true, player.hasMetadata(PersonalCreditListener.NPC_METADATA)));
    }

    private void look(Player player) {
        if (!player.isOnline()) {
            return;
        }
        Location at = player.getLocation();
        World world = at.getWorld();
        tracker.observe(player.getUniqueId(), world.getEnvironment() == World.Environment.NORMAL,
                player.getGameMode() == GameMode.SPECTATOR, at.getBlockX(), at.getBlockY(), at.getBlockZ(),
                (x, z) -> pieces(world, x, z));
    }

    /** Every piece of every Ancient City the chunk holding block {@code x z} references. */
    private List<BoundingBox> pieces(World world, int x, int z) {
        List<BoundingBox> boxes = new ArrayList<>();
        for (GeneratedStructure generated : world.getStructures(x >> 4, z >> 4, city)) {
            for (StructurePiece piece : generated.getPieces()) {
                boxes.add(piece.getBoundingBox());
            }
        }
        return boxes;
    }
}
